#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Henry Guan

# Short bio or description (displayed in the header)
description: University of Illinois Laboratory High School Class of 2027 student (Just a chill guy)

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

